Feature: Use LOA in permit application
As a user I need to use an active letter of authorization(LOA) in a permit application so that I can purchase a permit using the special authorization granted by the LOA.

Users = SA, HQA, PC, CTPO, Trainee, CA, PA 

@orv2-2261-1, @orv2-2860-6
Rule: The LOA(s) feature is hidden if there are no active or expired LOA(s)

  Scenario: no active LOA(s)
     When users apply for a permit
     Then option to use LOA(s) is not shown
     
  Scenario: active LOA(s) exist
    Given the active valid LOA(s) are for the permit type applied for
     When users apply for a permit
     Then they see a list of active LOA(s) that include:
       | data            | description                                                      |
       | LOA number      | the unique number generated by onRouteBC when the LOA is created |
       | LOA expiry date | the date the LOA expires                                         |
      And they see the "To find details about the LOA go to the Special Authorizations page." info box

  Scenario: available LOA(s)
    Given permit A uses LOA B
     When LOA B expires
      And staff amend permit A
     Then they see:
       | LOA B number      |
       | LOA B expiry date |
      And LOA B is unavailable
|
@orv2-2261-2, @orv2-2860-7
Rule: Using an LOA in a permit application is optional
|
@orv2-2261-3, @orv2-2860-8
Rule: No LOA is chosen by default when creating a new permit application 
|
@orv2-2261-4, @orv2-2860-9
Rule: A permit application can have only one LOA associated to it
|
@orv2-2261-5, @orv2-2860-10
Rule: LOA(s) must match the permit type to be available in the permit application

  Scenario: term LOA(s)
    Given the cv client has LOA(s) for term permits
     When users apply for a term permit
     Then they see the active LOA(s) for term permits

  Scenario: no term LOA(s)
    Given the cv client has no LOA(s) for term permits
     When users apply for a term permit
     Then option to use LOA(s) is not shown
|
@orv2-2261-6, @orv2-2860-11
Rule: LOA(s) must not be expired to be available in the permit application
 
  Scenario: LOA(s) expired before application
    Given a cv client has one LOA(s)
     And the LOA(s) expires on 02/01/2024
     When a user applies for a permit on 02/02/2024
     Then option to use LOA(s) is not shown

  Scenario: LOA(s) expires before minimum allowable permit term length
    Given a cv client has one LOA(s)
     And the LOA(s) expires on 02/28/2024
     When a user applies for a term permit on 02/02/2024
     Then the LOA(s) is shown
      But the LOA(s) cannot be chosen

  # deprecated
  # Scenario: LOA(s) has not started
    Given a cv client has one LOA(s)
     And the LOA(s) starts on 02/22/2025
     When a user applies for a term permit on 02/07/2025
     Then the LOA(s) cannot be chosen
|
@orv2-2261-7, @orv2-2860-12
Rule: Permit start date and duration are limited by the chosen LOA

  Scenario: LOA expires before maximum allowable term duration
    Given the chosen LOA expires on 04/01/2024 |
     When a user chooses a start date that is 01/11/2024
     Then they can choose only the following valid term durations:
       | 30 |
       | 60 |
|
@orv2-2261-8, @orv2-2860-13
Rule: Only the vehicle type and sub-type in the chosen LOA is available in the permit application

  Scenario: no LOA vehicle type in inventory
    Given a valid LOA is chosen
      But there are is no valid LOA vehicle type in inventory
     When a user looks for an LOA vehicle
     Then they cannot find the vehicle
|
@orv2-2261-9, @orv2-2860-14
Rule: Vehicle type and sub-type are inputted when an LOA is chosen and it is non editable

  Scenario: LOA chosen
     When a user choses a valid LOA
     Then the vehicle type and sub-type designated in the LOA are inputted
      And non-editable

  Scenario: LOA not chosen manual
    Given a user has not chosen an LOA
     When they choose a vehicle type and sub-type 
     Then all allowable vehicle types and sub-types are available

  Scenario: LOA not chosen recall
    Given a user has not chosen an LOA
     When they attempt to recall a vehicle
     Then all allowable vehicle types and sub-types are available from inventory

  Scenario: LOA unchosen
    Given a user has chosen an LOA A
      And there are vehicle details
     When they choose LOA B
     Then vehicle details are removed
      And the vehicle type and sub-type designated in the LOA B are inputted
      And non-editable
|
@orv2-2261-10, @orv2-2860-15
Rule: The user can review the chosen LOA parameters before completing the permit application workflow

  Scenario: LOA chosen
    Given the user has chosen an LOA
     When they review the inputted permit application parameters
     Then they see the following information about the LOA:
      | data       | description                                                                  |
      | LOA number | the unique number generated by onRouteBC when the LOA(s) is created by staff |
|
@orv2-2261-11, @orv2-2860-16
Rule: The chosen LOA number is printed on the issued permit pdf
|

See amend applications and shopping cart for additional specs