Feature: Manage waiting for payment (WFP) permit applications

Users: CA, PA, SA, PC, CTPO, Trainnee

@orv2-2412-1
Rule: Permit applications that fail permit payment confirmation are WFP

  Scenario: payment made onRouteBC receives no response
     When the user returns to onRouteBC
     Then they see the permit applications as WFP 

@orv2-2412-2
Rule: Show information about WFP permit applications

  Scenario: there are no WFP permit applications
     When users choose to view applications in progress
     Then they do not see the option to view WFP permit applications 

  Scenario: there are WFP permit applications
     When users choose to view WFP permit applications
     Then they see the following information listed for each WFP permit application:
       | data            | description                                                     |
       | Application No. | the permit applicationed number generated by onRouteBC          |
       | Permit Type     | the permit type acronym                                         |
       | Plate           | the vehicle plate no. in the permit application                 |
       | Applicant       | the BCeID username of the applicant OR Provincial Permit Centre |

 #default sort, pagination

@orv2-2412-3
Rule: Users can change one or more WFP permit applications to applications in progress (AIP)

  Scenario: change to AIP
    Given there are WFP permit applications
     When a user changes the WFP permit application to an AIP
     Then the WFP permit application is shown as an AIP
      And the WFP permit application is not shown as a WFP permit application

  Scenario: nothing selected
    Given a user has not chosen a WFP permit application to change
     When they choose to change a WFP permit application to an AIP
     Then they cannot continue
      And they see "Select at least one item"
      And the mandatory field is indicated

  Scenario: multiple selected
    Given there are 5 WFP permit applications chosen
     When a user changes the WFP permit application to an AIP
     Then the 5 WFP permit application chosen are shown as AIP
      And the 5 WFP permit application chosen are not shown as a WFP permit applications

