Feature: Manage applications in review

User = CA, PA, SA, PC, CTPO, Trainee

Rule: Users see spermit application submitted notification

Rule: User see a list of application in review with information about each

  Scenario: no applications in review
     When a user is chooses to view applications in review
     Then they see "No records found"

  Scenario: application in review exist
     When a user is chooses to view applications in review
     Then they see a list of applications in reivew with the following information per application:
       | information       | description                                                   |
       | Application #     | the unique application number generated by onRouteBC          |
       | Permit Type       | the type of permit application being applied for              |
       | Unit #            | the unit number of the power unit inputted in the application |
       | VIN               | the 6 digit VIN of the power unit inputted in the application |
       | Plate             | the plate of the power unit inputted in the application       |
       | Permit Start Date | the start date inputted by the applicant                      |
       | Last Updated      | the date the application in review was last saved             |

Rule: The application in review list default sort is by last updated date, newest at the top in descending order

Rule: The application in review list default pagination is 10 items

Rule: Users see the reject applications info box

Rule: An application that is not claimed by staff is "Pending Review"

  Scenario: apps pending review exist 
     When a user chooses to view applications in review
     Then they see the label "Pending Review"

  Scenario: application newly submitted
    Given application A1-72303011-028 is newly submitted for review
     When a user views the application in the list
     Then they see the label "Pending Review" next to A1-72303011-028

Rule: An application that is claimed by staff is "In Review"

  Scenario: apps in review exist 
     When a user chooses to view applications in review
     Then they see the label "In Review"

  Scenario: application claimed
    Given application A1-72303011-028 is claimed by staff
     When a user views the application in the list
     Then they see the label "In Review" next to A1-72303011-028

Rule: A user can withdraw a submitted permit application in pending review


Rule: A withdrawn submitted permit application is an application in progress


Rule: 



  Scenario: 
    Given 
     When 
     Then 

