@orv2-5400 https://onroutebc.atlassian.net/browse/ORV2-5400
Feature: As a user I need to be able to review and confirm my STOW permit application details so that I can submit it for review by the PPC or add it to the shopping cart.

user = PC, SA, TRAIN, CTPO, CA, PA

# Notes
 # see Staff Review and Confirm STOW.feature for staff review and confirm details
 # see CV Client Review and Confirm STOW.feature for CV client review and confirm details

# Show Information Inputted by the User and onRouteBC Generated Information
 @orv2-5400-1
 Rule: Show application details inputted by the user prior to submission or adding to cart

  Scenario: continue to review and confirm
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see:
        | Contact information submitted                              |
        | Permit details submitted                                   |
        | Chosen CVSE Forms listed with links to the source of truth |
        | Commodity details submitted                                |
        | Vehicle information submitted                              |
        | ASW data submitted                                         |
        | Extraordinary load request calculated if submitted         |
        | Trip details submitted                                     |
        | Application notes if submitted                             |

 @orv2-5400-2
 Rule: Show onRouteBC generated information to the user prior to submission or adding to cart

  Scenario: continue to review and confirm
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see:
        | Permit type name of chosen permit                                            |
        | Application # generated by onRouteBC                                         |
        | Date created date/time permit application created                            |
        | Last updated date/time of the last change saved                              |
        | Client name of the permittee profile                                         |
        | onRouteBC client number of the permittee profile                             |
        | Company mailing address of permitee profile                                  |
        | Contact information of the permittee profile (name, phone, client email)     |
        | Expiry date calculated based on the permit start date and duration submitted |
        | Default CVSE Forms listed with links to the source of truth                  |

# Overload and OCD
 @orv2-5400-3
 Rule: Show overload and OCD information to the user

   Scenario: overload
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see:
        | Total GCVW (kg) calculated from the ASW data submitted       |
        | Overload (kg) calculated from the ASW data submitted         |
        | OCD table showing overload calculation details submitted     |

# Calculation Results and Violations
 @orv2-5400-4
 Rule: If present, show policy violations and ASW indication to the user

   Scenario: violations
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see:
        | Violations calculated if present                 |
        | Violation indication on the ASW table if present |

# Compliance warnings
 @orv2-5400-5
 Rule: If present, show compliance warnings to the user

   Scenario: compliance warnings
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see: "Review Compliance Requirements Wheelbase for Axle Unit X and Axle Unit Y is between 6.2m and 7.2m. Semi-Trailer wheelbase must be within dimensions table found in CTPM 5.3.7.A."

# Attestations
 @orv2-5400-6
 Rule: The user must complete the attestations

  Scenario: Attestations
      Given a user has continued from the "Permit Application" page
      When they arrive at the "Review and Confirm Details" page
      Then they see a list of attestations they are required to check in order to proceed to pay
        | Confirm that this permit is issued to the registered owner (or lessee) of the vehicle being permitted. |
        | Confirm compliance with the appropriate policy for the selected vehicle(s) and/or commodity(s).        |
        | Confirm the information in this application is correct.                                                |

  Scenario: Attestations warning
      Given a user has not checked one or more attestations
      When they choose to continue
      Then they see "Checkbox selection is required"
       And the checkboxes are indicated

# Permit Fee
 @orv2-5400-7
 Rule: The overload permit fee is calculated using overload (kg) (or fraction thereof) x (the total distance (km) / 10) rounded to the nearest dollar with a minimum fee of $25.00

  # see General Fee 3(d) for current fee table: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/328_91

  Overload permit fee table:
     | overloadkg      | rateper10km |
     | 0-2000          | 0.95        |
     | 2001-3000       | 1.15        |
     | 3001-4000       | 1.40        |
     | 4001-5000       | 1.60        |
     | 5001-6000       | 1.85        |
     | 6001-7000       | 2.15        |
     | 7001-8000       | 2.45        |
     | 8001-9000       | 2.95        |
     | 9001-10000      | 3.35        |
     | 10001-11000     | 3.75        |
     | 11001-12000     | 4.25        |
     | 12001-13000     | 4.95        |
     | 13001-14000     | 5.60        |
     | 14001-15000     | 6.25        |
     | 15001-16000     | 7.25        |
     | 16001-17000     | 8.25        |
     | 17001-18000     | 9.15        |
     | 18001-19000     | 10.10       |
     | 19001-20000     | 10.90       |
     | 20001-21000     | 11.85       |
     | 21001-22000     | 12.70       |
     | 22001-23000     | 13.95       |
     | 23001-24000     | 14.95       |
     | 24001-25000     | 16.10       |
     | 25001-26000     | 17.85       |
     | 26001-27000     | 19.85       |
     | 27001-28000     | 21.40       |

   Scenario Outline: Overload permit fee is calculated from overload (kg) value and total distance
      Given a user has an overload <weight>kg
       And they have inputted <distance>km in total distance
      When they continue to the "Review and Confirm Details" page
      Then they see a overload permit fee of $<fee>
           
     Examples:
       | weight | distance | fee     |
       | 10000  | 800      | 268.00  |
       | 28000  | 1000     | 2140.00 |
       | 1000   | 100      | 25.00   |
       | 19500  | 900      | 981.00  |
       | 2000   | 101      | 25.00   |
       | 2001   | 220      | 25.00   |
       | 10001  | 800      | 300.00  |
       | 12000  | 85       | 36.00   |

 @orv2-5400-8
 Rule: For overload greater than 28000 kg, the permit fee per 10 km is 21.40 plus 1.85 for each 900 kg or portion thereof over 28000, with the minimum fee of 25.00, then rounded to the nearest dollar with amounts ending in 0.50 or more rounded up.

   Scenario Outline: Overload permit fee is calculated for overload greater than 28000 kg
      Given a users calculated <overload>kg
       And they have inputted <distance>km in total distance
      When they continue to the "Review and Confirm Details" page
      Then they see a overload permit fee of $<fee>

     Examples:
       | overload | distance | fee     |
       | 29000    | 1000     | 2510.00 |
       | 30700    | 100      | 270.00  |
       | 33400    | 100      | 330.00  | 

# Application Submission or Add to Cart
 # see 
 # - Staff Review and Confirm STOW.feature for staff review and confirm details
 # - CV Client Review and Confirm STOW.feature for CV client review and confirm details

