Feature: CV Client Manage Applications in Progress
   As a CV Client I want to view a list of my applications so that I can manage their submission, payment or deletion.

CV Client = CA and PA

@orv-548-1 @orv2-1575-1
Rule: Show list of applications in progress

  Scenario: View list applications do not exist
    Given the CV Client is at the "Applications in Progress" tab
     When they do not have applications in progress
     Then they see "No Records Found" empty state page message

  Scenario: View list applications exist
    Given CV Client has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see this data about applications
       | data                | description                                                                                   |
       | Application Number  | unique application no. generated by onRouteBC                                                 |
       | Permit Type         | the name of the permit applied for                                                            |
       | VIN                 | the first 6 digits of the ViN no. used in the application                                     |
       | Vehicle Plate       | the plate no. of the vehicle used in the application                                          |
       | Vehicle Unit Number | the unit no. of the vehicle used in the application                                           |
       | Last Updated Date   | the date the permit application was last updated                                              |
       | Permit Start Date   | the start date inputted in the permit application                                             |
       | Applicant           | the first name and last name of the logged in user that started the permit application or Provincial Permit Center if started by staff |
     And the default sort order is "Last Updated Date" newest at the top ascending


@orv-548-2
Rule: A CV Client PA can only view and edit applications they create

  Scenario: PA view list applications exist
    Given PA has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see only their applications

@orv-548-3
Rule: A CV Client CA can view the list of all applications created

  Scenario: CA view applications in progress
    Given CV Client has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see all applications created by CV Client users 
   
@orv-557-1
Rule: A CV Client CA can delete an application in progress started by a CV Client CA or PA

  Scenario: Bulk delete applications in progress
    Given the CV Client is at the "Applications in Progress" tab
     When they select one or more application
     And they choose to delete
     Then the applications are removed from the application in progress list
  
  Scenario: Delete application in progress
    Given the CV Client is at the "Applications in Progress" tab
     When they select a permit application
     And they choose to delete
    Then the applications are removed from the application in progress list

  Scenario: Started by staff
    Given application was started by staff
     When a CV Client CA chooses to delete the application
     Then they cannot delete the application

@orv2-685-1 @orv2-1575-2
Rule: A CV Client CA can edit application in progress started by a CV Client CA or PA 

  Scenario: CV Client started application
    Given the CV Client is at the "Applications in Progress" tab 
      And they have application in progress
     When they choose to view an application in progress
     Then they are directed to the selected "Permit Application" page 

   Scenario: Application started by staff
     Given the CV Client is at the "Applications in Progress" tab 
       And staff have applications in progress
      When they choose to edit a staff application in progress
      Then they cannot edit the application


  