Feature: CV Client Manage Applications in Progress
   As a CV Client I want to view a list of my applications so that I can manage their submission, payment or deletion.

CV Client = CA and PA

@orv-548-1 @orv2-1575-1
Rule: Show list of applications in progress

  Scenario: View list applications do not exist
    Given the CV Client is at the "Applications in Progress" tab
     When they do not have applications in progress
     Then they see "No Records Found" empty state page message

  Scenario: View list applications exist
    Given CV Client has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see this data about applications
       | data                | description                                                                                   |
       | Application Number  | unique application no. generated by onRouteBC                                                 |
       | Permit Type         | the name of the permit applied for                                                            |
       | VIN                 | the first 6 digits of the ViN no. used in the application                                     |
       | Vehicle Plate       | the plate no. of the vehicle used in the application                                          |
       | Vehicle Unit Number | the unit no. of the vehicle used in the application                                           |
       | Last Updated Date   | the date the permit application was last updated                                              |
       | Permit Start Date   | the start date inputted in the permit application                                             |
       | Applicant           | the first name and last name of the logged in user that started the permit application or Provincial Permit Center if started by staff |
     And the default sort order is "Last Updated Date" newest at the top ascending

@orv2-3071-1
Rule: Applicant is the user that creates the permit application

  Scenario: staff created permit application
     When cv client view applications in progress
     Then applicant is Provincial Permit Center

  Scenario: cv client created permit application
     When cv client view applications in progress
     Then applicant is logged in user first name last name

@orv-548-2
Rule: A CV Client PA can only view and edit applications they create

  Scenario: PA view list applications exist
    Given PA has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see only their applications

@orv-548-3
Rule: A CV Client CA can view the list of all applications created

  Scenario: CA view applications in progress
    Given CV Client has applications in progress
     When they are viewing the "Applications in Progress" tab
     Then they see all applications created by CV Client users 
   
@orv-557-1
Rule: A CV Client CA can delete an application in progress started by a CV Client CA or PA

  Scenario: Bulk delete applications in progress
    Given the CV Client is at the "Applications in Progress" tab
     When they select one or more application
     And they choose to delete
     Then the applications are removed from the application in progress list
  
  Scenario: Delete application in progress
    Given the CV Client is at the "Applications in Progress" tab
     When they select a permit application
     And they choose to delete
    Then the applications are removed from the application in progress list

  Scenario: Started by staff
    Given application was started by staff
     When a CV Client CA chooses to delete the application
     Then they cannot delete the application

@orv2-685-1 @orv2-1575-2
Rule: A CV Client CA can edit application in progress started by a CV Client CA or PA 

  Scenario: CV Client started application
    Given the CV Client is at the "Applications in Progress" tab 
      And they have application in progress
     When they choose to view an application in progress
     Then they are directed to the selected "Permit Application" page 

   Scenario: Application started by staff
     Given the CV Client is at the "Applications in Progress" tab 
       And staff have applications in progress
      When they choose to edit a staff application in progress
      Then they cannot edit the application
  
@orv2-5553-1
Rule: a rejected application in progress shows a rejected label

  Scenario: rejected application in progress
    Given the CV Client is at the "Applications in Progress" tab 
      And they have a rejected application in progress
     When they view the application in progress
     Then they see "R" (Rejected) label on the application

@orv2-5553-2
Rule: a rejected application in progress can be edited and added to cart for submission by staff only

  Scenario: rejected by staff then added to cart from AIP
    Given the CV Client is at the "Applications in Progress" tab 
      And they have a rejected application in progress
     When they view the application in progress
      And they choose to edit the application 
      And they add the edited rejected application to cart

@orv2-5553-3
Rule: a rejected application from queue shows rejected status in applications in progress

  Scenario: rejected from queue shows R in AIP
    Given the CV Client is at the "Applications in Progress" tab
      And they have an application rejected from queue
    When they view the application in progress
    Then they see "R" (Rejected) label on the application

  Scenario: non-rejected application does not show R in AIP
    Given the CV Client is at the "Applications in Progress" tab
      And they have an application in progress that is not rejected
    When they view the application in progress
    Then they do not see "R" (Rejected) label on the application

@orv2-5553-4
Rule: a rejected application submitted to applications in review shows status by claim state

  Scenario: rejected submitted to AIR shows PR when not claimed
    Given the CV Client has submitted a rejected application to "Applications in Review"
      And the application has not been claimed
    When they view the application in "Applications in Review"
    Then they see "PR" (Pending Review) status on the application

  Scenario: rejected submitted to AIR does not show PR when claimed
    Given the CV Client has submitted a rejected application to "Applications in Review"
      And the application has been claimed
    When they view the application in "Applications in Review"
    Then they do not see "PR" (Pending Review) status on the application
      And they see "IR" (In Review) status on the application

@orv2-5553-5
Rule: a rejected application withdrawn from applications in review back to applications in progress shows rejected label

  Scenario: rejected withdrawn from AIR to AIP shows R
    Given the CV Client has a rejected application in "Applications in Review"
    When the application is withdrawn to "Applications in Progress"
    Then they see "R" (Rejected) label on the application in "Applications in Progress"

  Scenario: withdrawn non-rejected application does not show R
    Given the CV Client has an application in "Applications in Review" that is not rejected
    When the application is withdrawn to "Applications in Progress"
    Then they do not see "R" (Rejected) label on the application in "Applications in Progress"

@orv2-5553-6
Rule: a rejected application approved to cart from queue and then removed from cart maintains rejection history without rejected label in applications in progress

  Scenario: approved to cart then removed keeps history and not R in AIP
    Given the CV Client has a rejected application submitted to "Applications in Review"
      And the application is claimed and approved to cart
    When they remove the approved application from cart
    Then rejection history is maintained on the application
      And they do not see "R" (Rejected) label on the application in "Applications in Progress"
      And they do not see a rejection banner on the application

  Scenario: approved to cart then removed does not lose rejection history
    Given the CV Client has a rejected application submitted to "Applications in Review"
      And the application is claimed and approved to cart
    When they remove the approved application from cart
    Then rejection history is maintained on the application

@orv2-5553-7
Rule: a rejected application added directly to cart by staff and removed from cart maintains rejection state in applications in progress

  Scenario: staff adds rejected application directly to cart and removed shows R in AIP
    Given staff has added a rejected application directly to cart from "Applications in Progress"
    When the application is removed from cart
    Then rejection history is maintained on the application
      And they see "R" (Rejected) label on the application in "Applications in Progress"
      And they see a rejection banner on the application

  Scenario: non-rejected staff direct-to-cart removed does not show rejection indicators
    Given staff has added an application that is not rejected directly to cart from "Applications in Progress"
    When the application is removed from cart
    Then they do not see "R" (Rejected) label on the application in "Applications in Progress"
      And they do not see a rejection banner on the application

